# Generated by Django 6.0 on 2025-12-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('contato_retorno', models.CharField(max_length=150)),
                ('mensagem', models.TextField(max_length=1000)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
